apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node-ingress
  annotations: 
     nginx.ingress.kubernetes.io/rewrite-target: /
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: hello-node
          servicePort: 8080
